# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
  vrum_api:
    container_name: diario-digital-api
    image: diario-digital-api
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile